spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysite?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true