spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysite?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#MD5盐值
password:
  salt: shotmoonsdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.
#Redis Config
redis:
  ip: 127.0.0.1
  port: 6379
  max:
    total: 20
    idle: 10
  min:
    idle: 2
  test:
    borrow: true
    return: false

